climate:
  - platform: thermostat
    name: "${name} Climate"
    id: ${name}_climate
    sensor: room_temperature_zone_1
    visual:
      min_temperature: 10
      max_temperature: 45
      temperature_step: 0.5

    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_cooling_off_time: 60s
    min_cooling_run_time: 60s
    min_idle_time: 30s

    # Wanneer HA een nieuwe target temperature instelt
    on_control:
      - number.set:
          id: hc_thermostat_target_temperature_zone_1
          value: !lambda |-
            // Gebruik de getter i.p.v. x.target_temperature
            if (x.get_target_temperature().has_value()) {
              return x.get_target_temperature().value();
            } else {
              // fallback: huidige waarde behouden
              return id(hc_thermostat_target_temperature_zone_1).state;
            }

    # Acties bij verwarmen
    heat_action:
      - select.set:
          id: ac_mode_zone_1
          option: "${heating_room}"
      - switch.turn_on: system_on_off

    # Acties bij koelen
    cool_action:
      - select.set:
          id: ac_mode_zone_1
          option: "${cooling_room}"
      - switch.turn_on: system_on_off

    # Idle (uit)
    idle_action:
      - switch.turn_off: system_on_off
