climate:
  - platform: thermostat
    name: "Ecodan Climate"
    id: ecodan_climate
    sensor: room_temperature_zone_1

    visual:
      min_temperature: 10.0
      max_temperature: 45.0
      temperature_step: 0.5

    min_heating_off_time: 60s
    min_heating_run_time: 60s
    min_cooling_off_time: 60s
    min_cooling_run_time: 60s
    min_idle_time: 30s

    on_control:
      - number.set:
          id: hc_thermostat_target_temperature_zone_1
          value: !lambda |-
            if (x.get_target_temperature().has_value()) {
              return x.get_target_temperature().value();
            } else {
              return id(hc_thermostat_target_temperature_zone_1).state;
            }
    heat_action:
      - select.set:
          id: ac_mode_zone_1
          option: heating_room
      - switch.turn_on: system_on_off

    cool_action:
      - select.set:
          id: ac_mode_zone_1
          option: cooling_flow
      - switch.turn_on: system_on_off

    idle_action:
      - switch.turn_off: system_on_off


sensor:
  - platform: modbus_controller
    modbus_controller_id: Ecodan
    id: operating_mode_raw
    name: "Operating Mode Raw"
    address: 26
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
    on_value:
      then:
        - if:
            condition:
              lambda: return x == 2;
            then:
              - climate.control:
                  id: ecodan_climate
                  mode: "HEAT"
        - if:
            condition:
              lambda: return x == 3;
            then:
              - climate.control:
                  id: ecodan_climate
                  mode: "COOL"
        - if:
            condition:
              lambda: return x == 0;
            then:
              - climate.control:
                  id: ecodan_climate
                  mode: "OFF"
