#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 raw 45"
  register_type: holding
  address: 45
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 CO2 test 45 x0.01"
  register_type: holding
  address: 45
  value_type: U_WORD
  unit_of_measurement: "ppm"
  filters:
    - multiply: 0.01
