#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 20s
    command_throttle: 200ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten
    
sensor:
  # Basis CO₂ (regs 4+5)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂"
    register_type: holding
    address: 4
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 1

  # Basis Temperatuur (regs 6+7)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur"
    register_type: holding
    address: 6
    value_type: FP32
    unit_of_measurement: "°C"
    accuracy_decimals: 1

  # Basis RV (regs 8+9)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV"
    register_type: holding
    address: 8
    value_type: FP32
    unit_of_measurement: "%"
    accuracy_decimals: 1

  # Extended Temperatuur (regs 1004+1005)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur Ext"
    register_type: holding
    address: 1004
    value_type: FP32
    unit_of_measurement: "°C"
    accuracy_decimals: 1

  # Extended RV (regs 1006+1007)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV Ext"
    register_type: holding
    address: 1006
    value_type: FP32
    unit_of_measurement: "%"
    accuracy_decimals: 1

  # Extended CO₂ (regs 1008+1009)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂ Ext"
    register_type: holding
    address: 1008
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 1
