#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 20s
    command_throttle: 200ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten
    
sensor:
  # Temperatuur (reg 38, U_WORD × 0.1) – reeds stabiel
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur"
    register_type: holding
    address: 38
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # CO₂ (reg 22, U_WORD × 0.1) – in-duct waarde
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂"
    register_type: holding
    address: 22
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  # --- RV raw kandidaten (nabij 18) ---
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 17"
    register_type: holding
    address: 17
    value_type: U_WORD
    unit_of_measurement: "raw"
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 18"
    register_type: holding
    address: 18
    value_type: U_WORD
    unit_of_measurement: "raw"
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 19"
    register_type: holding
    address: 19
    value_type: U_WORD
    unit_of_measurement: "raw"

  # --- CO₂ raw kandidaten (nabij 20) ---
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "CO2 raw 20"
    register_type: holding
    address: 20
    value_type: U_WORD
    unit_of_measurement: "raw"
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "CO2 raw 21"
    register_type: holding
    address: 21
    value_type: U_WORD
    unit_of_measurement: "raw"
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "CO2 raw 22"
    register_type: holding
    address: 22
    value_type: U_WORD
    unit_of_measurement: "raw"
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "CO2 raw 24"
    register_type: holding
    address: 24
    value_type: U_WORD
    unit_of_measurement: "raw"

  # --- Extended raw check (soms U_WORD) ---
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "Ext raw 1006"
    register_type: holding
    address: 1006
    value_type: U_WORD
    unit_of_measurement: "raw"
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "Ext raw 1008"
    register_type: holding
    address: 1008
    value_type: U_WORD
    unit_of_measurement: "raw"
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "Ext raw 1010"
    register_type: holding
    address: 1010
    value_type: U_WORD
    unit_of_measurement: "raw"
