#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 20s
    command_throttle: 200ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten
    
sensor:
  # Temperatuur via reg 38 (U_WORD × 0.1) – werkt al goed
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur"
    register_type: holding
    address: 38
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # --- RV tests ---
  # Huidige RV (U_WORD × 0.001)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV U_WORD"
    register_type: holding
    address: 18
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  # RV basis als FP32
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV FP32"
    register_type: holding
    address: 18
    value_type: FP32
    unit_of_measurement: "%"
    accuracy_decimals: 1

  # RV extended mapping (1006 FP32)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV Ext FP32"
    register_type: holding
    address: 1006
    value_type: FP32
    unit_of_measurement: "%"
    accuracy_decimals: 1

  # --- CO₂ tests ---
  # CO₂ basis mapping reg 4 (FP32)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂ FP32 reg4"
    register_type: holding
    address: 4
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 0

  # CO₂ basis mapping reg 20 (FP32)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂ FP32 reg20"
    register_type: holding
    address: 20
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 0

  # CO₂ extended mapping reg 1008 (FP32)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂ Ext FP32"
    register_type: holding
    address: 1008
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
