#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur"
    register_type: holding
    address: 38
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂"
    register_type: holding
    address: 22
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV actueel"
    register_type: holding
    address: 41
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV gem"
    register_type: holding
    address: 39
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  # tijdelijk: test CO2 registers rond 22
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 test 21"
    register_type: holding
    address: 21
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 test 23"
    register_type: holding
    address: 23
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 test 24"
    register_type: holding
    address: 24
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

