#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 20s
    command_throttle: 200ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten
    
sensor:
  # Basismapping CO₂ (4+5)    
  - platform: modbus_controller
    name: "TG9 CO₂"
    register_type: holding
    address: 4
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 1

  # Extended RH (1006+1007)
  - platform: modbus_controller
    name: "TG9 RV"
    register_type: holding
    address: 1006
    value_type: FP32
    unit_of_measurement: "%"
    accuracy_decimals: 2

  # Extended Temp (1004+1005)
  - platform: modbus_controller
    name: "TG9 Temperatuur"
    register_type: holding
    address: 1004
    value_type: FP32
    unit_of_measurement: "°C"
    accuracy_decimals: 1
