#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
# Debug: losse 16-bit words
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 raw 44"
  register_type: holding
  address: 44
  value_type: U_WORD
  unit_of_measurement: "raw"
  accuracy_decimals: 0

- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 raw 45"
  register_type: holding
  address: 45
  value_type: U_WORD
  unit_of_measurement: "raw"
  accuracy_decimals: 0

# Productie: CO2 candidate (16-bit on register 45) -> schaalfactor 0.01
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 CO₂"
  register_type: holding
  address: 45
  value_type: U_WORD
  unit_of_measurement: "ppm"
  accuracy_decimals: 0
  filters:
    - multiply: 0.01

# Debug: gecombineerde 32-bit (uitgeschakeld / optioneel)
# Gebruik alleen tijdelijk om te testen; laat uit of commentaar verwijderen in productie
# - platform: modbus_controller
#   modbus_controller_id: Tongdy_TG9
#   name: "TG9 CO2 test U_DWORD_R @44"
#   register_type: holding
#   address: 44
#   value_type: U_DWORD_R
#   unit_of_measurement: "raw"
#   accuracy_decimals: 0

# Temperatuur debug / kandidaat (raw 38)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 raw 38"
  register_type: holding
  address: 38
  value_type: U_WORD
  unit_of_measurement: "raw"
  accuracy_decimals: 0

- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 Temperature test 38 x0.1"
  register_type: holding
  address: 38
  value_type: U_WORD
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1

# RV (rel. vochtigheid) kandidaat op register 41
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 RV test 41 x0.001"
  register_type: holding
  address: 41
  value_type: U_WORD
  unit_of_measurement: "%"
  accuracy_decimals: 2
  filters:
    - multiply: 0.001
