#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
# andere 32-bit interpretaties
- name: "TG9 CO2 test U_DWORD @44"
  address: 44
  value_type: U_DWORD

- name: "TG9 CO2 test U_DWORD_SWAP @44"
  address: 44
  value_type: U_DWORD_S   # als ESPHome variant voor word-swap beschikbaar is

- name: "TG9 CO2 test FP32_R @44"
  address: 44
  value_type: FP32_R

- name: "TG9 CO2 test FP32 @44"
  address: 44
  value_type: FP32
