#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur"
    register_type: holding
    address: 38
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂"
    register_type: holding
    address: 22
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV actueel"
    register_type: holding
    address: 41
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV gem"
    register_type: holding
    address: 39
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  # tijdelijk: test CO2 registers rond 22
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 test 21"
    register_type: holding
    address: 21
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 test 23"
    register_type: holding
    address: 23
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 test 24"
    register_type: holding
    address: 24
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  # raw scan registers 30-45 (geen schaal) — maakt duidelijk welke raw waarden veranderen
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 30"
    register_type: holding
    address: 30
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 31"
    register_type: holding
    address: 31
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 32"
    register_type: holding
    address: 32
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 33"
    register_type: holding
    address: 33
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 34"
    register_type: holding
    address: 34
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 35"
    register_type: holding
    address: 35
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 36"
    register_type: holding
    address: 36
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 37"
    register_type: holding
    address: 37
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 38"
    register_type: holding
    address: 38
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 39"
    register_type: holding
    address: 39
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 40"
    register_type: holding
    address: 40
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 41"
    register_type: holding
    address: 41
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 42"
    register_type: holding
    address: 42
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 43"
    register_type: holding
    address: 43
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 44"
    register_type: holding
    address: 44
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 raw 45"
    register_type: holding
    address: 45
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 raw 22"
    register_type: holding
    address: 22
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 raw 23"
    register_type: holding
    address: 23
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 dword 22 U_DWORD_R"
    register_type: holding
    address: 22
    value_type: U_DWORD_R

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 float 22 FP32"
    register_type: holding
    address: 22
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO2 float 22 FP32_R"
    register_type: holding
    address: 22
    value_type: FP32_R
    unit_of_measurement: "ppm"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂ test 45"
    register_type: holding
    address: 45
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.01
