#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 raw 44"
  register_type: holding
  address: 44
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 raw 45"
  register_type: holding
  address: 45
  value_type: U_WORD

# tijdelijke test (geen multiply)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 CO2 test 45 raw"
  register_type: holding
  address: 45
  value_type: U_WORD
