#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 20s
    command_throttle: 200ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten
    
sensor:
  # Temperatuur via reg 38
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur"
    register_type: holding
    address: 38
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # RV via reg 18 (correcte schaal)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV"
    register_type: holding
    address: 18
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  # CO₂ via reg 20 (test FP32)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂"
    register_type: holding
    address: 20
    value_type: FP32
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
