#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 350ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur 9"
    address: 9         # als fabrikant 1-based telt
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur 10"
    address: 10         # als fabrikant 1-based telt
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "Relatieve Vochtigheid"
    address: 11
    register_type: read      # function 4
    value_type: U_WORD       # unsigned 16-bit
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1        # waarde is x10 geschaald
