#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten

sensor:
  - platform: modbus_controller
    modbus_controller_id: tg9_sensor
    name: "TG9 Relative Humidity"
    register_type: holding
    address: 18
    value_type: U_WORD
    accuracy_decimals: 1
    multiply: 0.1
    unit_of_measurement: "%"
    polling_interval: 5s
