#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 20s
    command_throttle: 200ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten

sensor:
  # Temperatuur (reg 38, U_WORD × 0.1)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 Temperatuur"
    register_type: holding
    address: 38
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # CO₂ (reg 22, U_WORD × 0.1)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 CO₂"
    register_type: holding
    address: 22
    value_type: U_WORD
    unit_of_measurement: "ppm"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

  # Relatieve vochtigheid (reg 18, U_WORD × 0.001)
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "TG9 RV"
    register_type: holding
    address: 18
    value_type: U_WORD
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  # Kandidaten rond temperatuur
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 36"
    register_type: holding
    address: 36
    value_type: U_WORD
    unit_of_measurement: "raw"

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 37"
    register_type: holding
    address: 37
    value_type: U_WORD
    unit_of_measurement: "raw"

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 39"
    register_type: holding
    address: 39
    value_type: U_WORD
    unit_of_measurement: "raw"

  # Kandidaten rond CO₂
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 23"
    register_type: holding
    address: 23
    value_type: U_WORD
    unit_of_measurement: "raw"

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 24"
    register_type: holding
    address: 24
    value_type: U_WORD
    unit_of_measurement: "raw"

  # Extra kandidaten rond 39
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 40"
    register_type: holding
    address: 40
    value_type: U_WORD
    unit_of_measurement: "raw"

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 41"
    register_type: holding
    address: 41
    value_type: U_WORD
    unit_of_measurement: "raw"

  # Kandidaten rond 60
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 60"
    register_type: holding
    address: 60
    value_type: U_WORD
    unit_of_measurement: "raw"

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 61"
    register_type: holding
    address: 61
    value_type: U_WORD
    unit_of_measurement: "raw"

  # Kandidaten rond 120
  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 120"
    register_type: holding
    address: 120
    value_type: U_WORD
    unit_of_measurement: "raw"

  - platform: modbus_controller
    modbus_controller_id: Tongdy_TG9
    name: "RV raw 121"
    register_type: holding
    address: 121
    value_type: U_WORD
    unit_of_measurement: "raw"

