#### Tongdy TG Air quality transmitter ####

modbus_controller:
  - id: Tongdy_TG9
    address: 12
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    command_throttle: 200ms
    # timeout: 400ms  # optioneel bij trage apparaten

sensor:
# --- CO₂ ---
# 16-bit variant (Register 8, UINT16)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 CO₂ (U_WORD)"
  register_type: holding
  address: 8
  value_type: U_WORD
  unit_of_measurement: "ppm"
  accuracy_decimals: 0
  filters:
    - multiply: 0.01

# 32-bit float variant (Register 0, Float-Inverse)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 CO₂ (FP32_R)"
  register_type: holding
  address: 0
  value_type: FP32_R
  unit_of_measurement: "ppm"
  accuracy_decimals: 1

# --- Temperatuur ---
# 16-bit variant (Register 10, signed INT ×10)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 Temperatuur (S_WORD)"
  register_type: holding
  address: 10
  value_type: S_WORD
  unit_of_measurement: "°C"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1

# 32-bit float variant (Register 4, Float-Inverse)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 Temperatuur (FP32_R)"
  register_type: holding
  address: 4
  value_type: FP32_R
  unit_of_measurement: "°C"
  accuracy_decimals: 1

# --- Relatieve Vochtigheid ---
# 16-bit variant (Register 11, UINT16 ×10)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 RV (U_WORD)"
  register_type: holding
  address: 11
  value_type: U_WORD
  unit_of_measurement: "%"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1

# 32-bit float variant (Register 6, Float-Inverse)
- platform: modbus_controller
  modbus_controller_id: Tongdy_TG9
  name: "TG9 RV (FP32_R)"
  register_type: holding
  address: 6
  value_type: FP32_R
  unit_of_measurement: "%"
  accuracy_decimals: 1
