modbus_controller:
  - id: slave_1
    address: 1
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_2
    address: 2
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_3
    address: 3
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_4
    address: 4
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_5
    address: 5
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_6
    address: 6
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_7
    address: 7
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_8
    address: 8
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_9
    address: 9
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_10
    address: 10
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_11
    address: 11
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_12
    address: 12
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_13
    address: 13
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_14
    address: 14
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_15
    address: 15
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_16
    address: 16
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_17
    address: 17
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_18
    address: 18
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms
  - id: slave_19
    address: 19
    modbus_id: modbus1
    update_interval: 100s
    command_throttle: 350ms

sensor:
  - platform: modbus_controller
    name: "Slave 1 Holding Reg 0"
    modbus_controller_id: slave_1
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 1 Holding Reg 8"
    modbus_controller_id: slave_1
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 1 Holding Reg 100"
    modbus_controller_id: slave_1
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 2 Holding Reg 0"
    modbus_controller_id: slave_2
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 2 Holding Reg 8"
    modbus_controller_id: slave_2
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 2 Holding Reg 100"
    modbus_controller_id: slave_2
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 3 Holding Reg 0"
    modbus_controller_id: slave_3
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 3 Holding Reg 8"
    modbus_controller_id: slave_3
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 3 Holding Reg 100"
    modbus_controller_id: slave_3
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 4 Holding Reg 0"
    modbus_controller_id: slave_4
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 4 Holding Reg 8"
    modbus_controller_id: slave_4
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 4 Holding Reg 100"
    modbus_controller_id: slave_4
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 5 Holding Reg 0"
    modbus_controller_id: slave_5
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 5 Holding Reg 8"
    modbus_controller_id: slave_5
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 5 Holding Reg 100"
    modbus_controller_id: slave_5
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 6 Holding Reg 0"
    modbus_controller_id: slave_6
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 6 Holding Reg 8"
    modbus_controller_id: slave_6
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 6 Holding Reg 100"
    modbus_controller_id: slave_6
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 7 Holding Reg 0"
    modbus_controller_id: slave_7
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 7 Holding Reg 8"
    modbus_controller_id: slave_7
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 7 Holding Reg 100"
    modbus_controller_id: slave_7
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 8 Holding Reg 0"
    modbus_controller_id: slave_8
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 8 Holding Reg 8"
    modbus_controller_id: slave_8
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 8 Holding Reg 100"
    modbus_controller_id: slave_8
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 9 Holding Reg 0"
    modbus_controller_id: slave_9
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 9 Holding Reg 8"
    modbus_controller_id: slave_9
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 9 Holding Reg 100"
    modbus_controller_id: slave_9
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Tongdy Slave 9 Reg 1"
    modbus_controller_id: slave_9
    address: 1
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Tongdy Slave 9 Reg 2"
    modbus_controller_id: slave_9
    address: 2
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Tongdy Slave 9 Reg 3"
    modbus_controller_id: slave_9
    address: 3
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Tongdy Slave 9 Reg 4"
    modbus_controller_id: slave_9
    address: 4
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Tongdy Slave 9 Reg 5"
    modbus_controller_id: slave_9
    address: 5
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 10 Holding Reg 0"
    modbus_controller_id: slave_10
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 10 Holding Reg 8"
    modbus_controller_id: slave_10
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 10 Holding Reg 100"
    modbus_controller_id: slave_10
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 11 Holding Reg 0"
    modbus_controller_id: slave_11
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 11 Holding Reg 8"
    modbus_controller_id: slave_11
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 11 Holding Reg 100"
    modbus_controller_id: slave_11
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 12 Holding Reg 0"
    modbus_controller_id: slave_12
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 12 Holding Reg 8"
    modbus_controller_id: slave_12
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 12 Holding Reg 100"
    modbus_controller_id: slave_12
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 13 Holding Reg 0"
    modbus_controller_id: slave_13
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 13 Holding Reg 8"
    modbus_controller_id: slave_13
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 13 Holding Reg 100"
    modbus_controller_id: slave_13
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Brink Slave 13 Reg 10"
    modbus_controller_id: slave_13
    address: 10
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Brink Slave 13 Reg 11"
    modbus_controller_id: slave_13
    address: 11
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Brink Slave 13 Reg 12"
    modbus_controller_id: slave_13
    address: 12
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Brink Slave 13 Reg 13"
    modbus_controller_id: slave_13
    address: 13
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Brink Slave 13 Reg 14"
    modbus_controller_id: slave_13
    address: 14
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 14 Holding Reg 0"
    modbus_controller_id: slave_14
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 14 Holding Reg 8"
    modbus_controller_id: slave_14
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 14 Holding Reg 100"
    modbus_controller_id: slave_14
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 15 Holding Reg 0"
    modbus_controller_id: slave_15
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 15 Holding Reg 8"
    modbus_controller_id: slave_15
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 15 Holding Reg 100"
    modbus_controller_id: slave_15
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 16 Holding Reg 0"
    modbus_controller_id: slave_16
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 16 Holding Reg 8"
    modbus_controller_id: slave_16
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 16 Holding Reg 100"
    modbus_controller_id: slave_16
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 17 Holding Reg 0"
    modbus_controller_id: slave_17
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 17 Holding Reg 8"
    modbus_controller_id: slave_17
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 17 Holding Reg 100"
    modbus_controller_id: slave_17
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 18 Holding Reg 0"
    modbus_controller_id: slave_18
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 18 Holding Reg 8"
    modbus_controller_id: slave_18
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 18 Holding Reg 100"
    modbus_controller_id: slave_18
    address: 100
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 19 Holding Reg 0"
    modbus_controller_id: slave_19
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 19 Holding Reg 8"
    modbus_controller_id: slave_19
    address: 8
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 19 Holding Reg 100"
    modbus_controller_id: slave_19
    address: 100
    register_type: holding
    value_type: U_WORD
