modbus_controller:
  - id: slave_1
    address: 1
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_2
    address: 2
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_3
    address: 3
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_4
    address: 4
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_5
    address: 5
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_6
    address: 6
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_7
    address: 7
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_8
    address: 8
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_9
    address: 9
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_10
    address: 10
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_11
    address: 11
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_12
    address: 12
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_13
    address: 13
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_14
    address: 14
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_15
    address: 15
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_16
    address: 16
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_17
    address: 17
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_18
    address: 18
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_19
    address: 19
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_20
    address: 20
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_21
    address: 21
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_22
    address: 22
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_23
    address: 23
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_24
    address: 24
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_25
    address: 25
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_26
    address: 26
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_27
    address: 27
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_28
    address: 28
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_29
    address: 29
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_30
    address: 30
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_31
    address: 31
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_32
    address: 32
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_33
    address: 33
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_34
    address: 34
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_35
    address: 35
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_36
    address: 36
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_37
    address: 37
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_38
    address: 38
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_39
    address: 39
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_40
    address: 40
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_41
    address: 41
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_42
    address: 42
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_43
    address: 43
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_44
    address: 44
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_45
    address: 45
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_46
    address: 46
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_47
    address: 47
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_48
    address: 48
    modbus_id: modbus1
    update_interval: 100s
  - id: slave_49
    address: 49
    modbus_id: modbus1
    update_interval: 100s

sensor:
  - platform: modbus_controller
    name: "Slave 1 Holding Reg 0"
    modbus_controller_id: slave_1
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 2 Holding Reg 0"
    modbus_controller_id: slave_2
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 3 Holding Reg 0"
    modbus_controller_id: slave_3
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 4 Holding Reg 0"
    modbus_controller_id: slave_4
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 5 Holding Reg 0"
    modbus_controller_id: slave_5
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 6 Holding Reg 0"
    modbus_controller_id: slave_6
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 7 Holding Reg 0"
    modbus_controller_id: slave_7
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 8 Holding Reg 0"
    modbus_controller_id: slave_8
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 9 Holding Reg 0"
    modbus_controller_id: slave_9
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 10 Holding Reg 0"
    modbus_controller_id: slave_10
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 11 Holding Reg 0"
    modbus_controller_id: slave_11
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 12 Holding Reg 0"
    modbus_controller_id: slave_12
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 13 Holding Reg 0"
    modbus_controller_id: slave_13
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 14 Holding Reg 0"
    modbus_controller_id: slave_14
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 15 Holding Reg 0"
    modbus_controller_id: slave_15
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 16 Holding Reg 0"
    modbus_controller_id: slave_16
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 17 Holding Reg 0"
    modbus_controller_id: slave_17
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 18 Holding Reg 0"
    modbus_controller_id: slave_18
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 19 Holding Reg 0"
    modbus_controller_id: slave_19
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 20 Holding Reg 0"
    modbus_controller_id: slave_20
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 21 Holding Reg 0"
    modbus_controller_id: slave_21
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 22 Holding Reg 0"
    modbus_controller_id: slave_22
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 23 Holding Reg 0"
    modbus_controller_id: slave_23
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 24 Holding Reg 0"
    modbus_controller_id: slave_24
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 25 Holding Reg 0"
    modbus_controller_id: slave_25
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 26 Holding Reg 0"
    modbus_controller_id: slave_26
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 27 Holding Reg 0"
    modbus_controller_id: slave_27
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 28 Holding Reg 0"
    modbus_controller_id: slave_28
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 29 Holding Reg 0"
    modbus_controller_id: slave_29
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 30 Holding Reg 0"
    modbus_controller_id: slave_30
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 31 Holding Reg 0"
    modbus_controller_id: slave_31
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 32 Holding Reg 0"
    modbus_controller_id: slave_32
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 33 Holding Reg 0"
    modbus_controller_id: slave_33
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 34 Holding Reg 0"
    modbus_controller_id: slave_34
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 35 Holding Reg 0"
    modbus_controller_id: slave_35
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 36 Holding Reg 0"
    modbus_controller_id: slave_36
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 37 Holding Reg 0"
    modbus_controller_id: slave_37
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 38 Holding Reg 0"
    modbus_controller_id: slave_38
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 39 Holding Reg 0"
    modbus_controller_id: slave_39
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 40 Holding Reg 0"
    modbus_controller_id: slave_40
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 41 Holding Reg 0"
    modbus_controller_id: slave_41
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 42 Holding Reg 0"
    modbus_controller_id: slave_42
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 43 Holding Reg 0"
    modbus_controller_id: slave_43
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 44 Holding Reg 0"
    modbus_controller_id: slave_44
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 45 Holding Reg 0"
    modbus_controller_id: slave_45
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 46 Holding Reg 0"
    modbus_controller_id: slave_46
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 47 Holding Reg 0"
    modbus_controller_id: slave_47
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 48 Holding Reg 0"
    modbus_controller_id: slave_48
    address: 0
    register_type: holding
    value_type: U_WORD
  - platform: modbus_controller
    name: "Slave 49 Holding Reg 0"
    modbus_controller_id: slave_49
    address: 0
    register_type: holding
    value_type: U_WORD
